export enum EstadoPaquete {
  EN_CARGA = 'EN_CARGA',

  FP_GENERADO = 'FP_GENERADO',

  FACTURADO = 'FACTURADO',

  PAGO_MUTUAL = 'PAGO_MUTUAL',

  LIQUIDADA_A_SOCIOS = 'LIQUIDADA_A_SOCIOS',

  ARCHIVADO = 'ARCHIVADO',
}
