package absl.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BioquimicoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBioquimicoAllPropertiesEquals(Bioquimico expected, Bioquimico actual) {
        assertBioquimicoAutoGeneratedPropertiesEquals(expected, actual);
        assertBioquimicoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBioquimicoAllUpdatablePropertiesEquals(Bioquimico expected, Bioquimico actual) {
        assertBioquimicoUpdatableFieldsEquals(expected, actual);
        assertBioquimicoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBioquimicoAutoGeneratedPropertiesEquals(Bioquimico expected, Bioquimico actual) {
        assertThat(actual)
            .as("Verify Bioquimico auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBioquimicoUpdatableFieldsEquals(Bioquimico expected, Bioquimico actual) {
        assertThat(actual)
            .as("Verify Bioquimico relevant properties")
            .satisfies(a -> assertThat(a.getMatricula()).as("check matricula").isEqualTo(expected.getMatricula()))
            .satisfies(a -> assertThat(a.getCuit()).as("check cuit").isEqualTo(expected.getCuit()))
            .satisfies(a -> assertThat(a.getTipoIva()).as("check tipoIva").isEqualTo(expected.getTipoIva()))
            .satisfies(a ->
                assertThat(a.getDomicilioProfesional()).as("check domicilioProfesional").isEqualTo(expected.getDomicilioProfesional())
            )
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getFechaIngreso()).as("check fechaIngreso").isEqualTo(expected.getFechaIngreso()))
            .satisfies(a -> assertThat(a.getTelefono()).as("check telefono").isEqualTo(expected.getTelefono()))
            .satisfies(a -> assertThat(a.getNombreEnDosep()).as("check nombreEnDosep").isEqualTo(expected.getNombreEnDosep()))
            .satisfies(a -> assertThat(a.getNroPrestadorOsde()).as("check nroPrestadorOsde").isEqualTo(expected.getNroPrestadorOsde()))
            .satisfies(a -> assertThat(a.getIngBrutos()).as("check ingBrutos").isEqualTo(expected.getIngBrutos()))
            .satisfies(a -> assertThat(a.getNroJubilacion()).as("check nroJubilacion").isEqualTo(expected.getNroJubilacion()))
            .satisfies(a -> assertThat(a.getNroLaboratorio()).as("check nroLaboratorio").isEqualTo(expected.getNroLaboratorio()))
            .satisfies(a -> assertThat(a.getGenero()).as("check genero").isEqualTo(expected.getGenero()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBioquimicoUpdatableRelationshipsEquals(Bioquimico expected, Bioquimico actual) {
        // empty method
    }
}
