package absl.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MutualAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMutualAllPropertiesEquals(Mutual expected, Mutual actual) {
        assertMutualAutoGeneratedPropertiesEquals(expected, actual);
        assertMutualAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMutualAllUpdatablePropertiesEquals(Mutual expected, Mutual actual) {
        assertMutualUpdatableFieldsEquals(expected, actual);
        assertMutualUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMutualAutoGeneratedPropertiesEquals(Mutual expected, Mutual actual) {
        assertThat(actual)
            .as("Verify Mutual auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMutualUpdatableFieldsEquals(Mutual expected, Mutual actual) {
        assertThat(actual)
            .as("Verify Mutual relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getCuit()).as("check cuit").isEqualTo(expected.getCuit()))
            .satisfies(a -> assertThat(a.getTipoIva()).as("check tipoIva").isEqualTo(expected.getTipoIva()))
            .satisfies(a -> assertThat(a.getDomicilio()).as("check domicilio").isEqualTo(expected.getDomicilio()))
            .satisfies(a -> assertThat(a.getTelefono()).as("check telefono").isEqualTo(expected.getTelefono()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getHabilitada()).as("check habilitada").isEqualTo(expected.getHabilitada()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMutualUpdatableRelationshipsEquals(Mutual expected, Mutual actual) {
        // empty method
    }
}
