package absl.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NomencladorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNomencladorAllPropertiesEquals(Nomenclador expected, Nomenclador actual) {
        assertNomencladorAutoGeneratedPropertiesEquals(expected, actual);
        assertNomencladorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNomencladorAllUpdatablePropertiesEquals(Nomenclador expected, Nomenclador actual) {
        assertNomencladorUpdatableFieldsEquals(expected, actual);
        assertNomencladorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNomencladorAutoGeneratedPropertiesEquals(Nomenclador expected, Nomenclador actual) {
        assertThat(actual)
            .as("Verify Nomenclador auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNomencladorUpdatableFieldsEquals(Nomenclador expected, Nomenclador actual) {
        assertThat(actual)
            .as("Verify Nomenclador relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNomencladorUpdatableRelationshipsEquals(Nomenclador expected, Nomenclador actual) {
        assertThat(actual)
            .as("Verify Nomenclador relationships")
            .satisfies(a -> assertThat(a.getMutual()).as("check mutual").isEqualTo(expected.getMutual()));
    }
}
