package absl.domain;

import static absl.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class OrdenAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrdenAllPropertiesEquals(Orden expected, Orden actual) {
        assertOrdenAutoGeneratedPropertiesEquals(expected, actual);
        assertOrdenAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrdenAllUpdatablePropertiesEquals(Orden expected, Orden actual) {
        assertOrdenUpdatableFieldsEquals(expected, actual);
        assertOrdenUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrdenAutoGeneratedPropertiesEquals(Orden expected, Orden actual) {
        assertThat(actual)
            .as("Verify Orden auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrdenUpdatableFieldsEquals(Orden expected, Orden actual) {
        assertThat(actual)
            .as("Verify Orden relevant properties")
            .satisfies(a -> assertThat(a.getAfiliado()).as("check afiliado").isEqualTo(expected.getAfiliado()))
            .satisfies(a -> assertThat(a.getProtocolo()).as("check protocolo").isEqualTo(expected.getProtocolo()))
            .satisfies(a -> assertThat(a.getFechaOrden()).as("check fechaOrden").isEqualTo(expected.getFechaOrden()))
            .satisfies(a -> assertThat(a.getFechaPrescripcion()).as("check fechaPrescripcion").isEqualTo(expected.getFechaPrescripcion()))
            .satisfies(a ->
                assertThat(a.getTotalOrden())
                    .as("check totalOrden")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalOrden())
            )
            .satisfies(a ->
                assertThat(a.getSumaUb()).as("check sumaUb").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSumaUb())
            )
            .satisfies(a -> assertThat(a.getFechaCreacion()).as("check fechaCreacion").isEqualTo(expected.getFechaCreacion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrdenUpdatableRelationshipsEquals(Orden expected, Orden actual) {
        assertThat(actual)
            .as("Verify Orden relationships")
            .satisfies(a -> assertThat(a.getPaquete()).as("check paquete").isEqualTo(expected.getPaquete()))
            .satisfies(a -> assertThat(a.getUsuario()).as("check usuario").isEqualTo(expected.getUsuario()))
            .satisfies(a -> assertThat(a.getBioquimico()).as("check bioquimico").isEqualTo(expected.getBioquimico()));
    }
}
