package absl.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PaqueteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaqueteAllPropertiesEquals(Paquete expected, Paquete actual) {
        assertPaqueteAutoGeneratedPropertiesEquals(expected, actual);
        assertPaqueteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaqueteAllUpdatablePropertiesEquals(Paquete expected, Paquete actual) {
        assertPaqueteUpdatableFieldsEquals(expected, actual);
        assertPaqueteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaqueteAutoGeneratedPropertiesEquals(Paquete expected, Paquete actual) {
        assertThat(actual)
            .as("Verify Paquete auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaqueteUpdatableFieldsEquals(Paquete expected, Paquete actual) {
        assertThat(actual)
            .as("Verify Paquete relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getPeriodo()).as("check periodo").isEqualTo(expected.getPeriodo()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getTipoIva()).as("check tipoIva").isEqualTo(expected.getTipoIva()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaqueteUpdatableRelationshipsEquals(Paquete expected, Paquete actual) {
        assertThat(actual)
            .as("Verify Paquete relationships")
            .satisfies(a -> assertThat(a.getPlan()).as("check plan").isEqualTo(expected.getPlan()));
    }
}
