package absl.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlanMutualAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanMutualAllPropertiesEquals(PlanMutual expected, PlanMutual actual) {
        assertPlanMutualAutoGeneratedPropertiesEquals(expected, actual);
        assertPlanMutualAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanMutualAllUpdatablePropertiesEquals(PlanMutual expected, PlanMutual actual) {
        assertPlanMutualUpdatableFieldsEquals(expected, actual);
        assertPlanMutualUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanMutualAutoGeneratedPropertiesEquals(PlanMutual expected, PlanMutual actual) {
        assertThat(actual)
            .as("Verify PlanMutual auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanMutualUpdatableFieldsEquals(PlanMutual expected, PlanMutual actual) {
        assertThat(actual)
            .as("Verify PlanMutual relevant properties")
            .satisfies(a -> assertThat(a.getCategoria()).as("check categoria").isEqualTo(expected.getCategoria()))
            .satisfies(a -> assertThat(a.getEtiquetaReporte()).as("check etiquetaReporte").isEqualTo(expected.getEtiquetaReporte()))
            .satisfies(a ->
                assertThat(a.getPrestacionesImportadas()).as("check prestacionesImportadas").isEqualTo(expected.getPrestacionesImportadas())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanMutualUpdatableRelationshipsEquals(PlanMutual expected, PlanMutual actual) {
        assertThat(actual)
            .as("Verify PlanMutual relationships")
            .satisfies(a -> assertThat(a.getMutual()).as("check mutual").isEqualTo(expected.getMutual()));
    }
}
