package absl.domain;

import static absl.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PracticaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPracticaAllPropertiesEquals(Practica expected, Practica actual) {
        assertPracticaAutoGeneratedPropertiesEquals(expected, actual);
        assertPracticaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPracticaAllUpdatablePropertiesEquals(Practica expected, Practica actual) {
        assertPracticaUpdatableFieldsEquals(expected, actual);
        assertPracticaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPracticaAutoGeneratedPropertiesEquals(Practica expected, Practica actual) {
        assertThat(actual)
            .as("Verify Practica auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPracticaUpdatableFieldsEquals(Practica expected, Practica actual) {
        assertThat(actual)
            .as("Verify Practica relevant properties")
            .satisfies(a -> assertThat(a.getCantidad()).as("check cantidad").isEqualTo(expected.getCantidad()))
            .satisfies(a ->
                assertThat(a.getPvalor()).as("check pvalor").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPvalor())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPracticaUpdatableRelationshipsEquals(Practica expected, Practica actual) {
        assertThat(actual)
            .as("Verify Practica relationships")
            .satisfies(a -> assertThat(a.getPrestacion()).as("check prestacion").isEqualTo(expected.getPrestacion()))
            .satisfies(a -> assertThat(a.getOrden()).as("check orden").isEqualTo(expected.getOrden()));
    }
}
