package absl.domain;

import static absl.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PrestacionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrestacionAllPropertiesEquals(Prestacion expected, Prestacion actual) {
        assertPrestacionAutoGeneratedPropertiesEquals(expected, actual);
        assertPrestacionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrestacionAllUpdatablePropertiesEquals(Prestacion expected, Prestacion actual) {
        assertPrestacionUpdatableFieldsEquals(expected, actual);
        assertPrestacionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrestacionAutoGeneratedPropertiesEquals(Prestacion expected, Prestacion actual) {
        assertThat(actual)
            .as("Verify Prestacion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrestacionUpdatableFieldsEquals(Prestacion expected, Prestacion actual) {
        assertThat(actual)
            .as("Verify Prestacion relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getCodigoInos()).as("check codigoInos").isEqualTo(expected.getCodigoInos()))
            .satisfies(a ->
                assertThat(a.getValorUb()).as("check valorUb").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getValorUb())
            )
            .satisfies(a -> assertThat(a.getReqAutorizacion()).as("check reqAutorizacion").isEqualTo(expected.getReqAutorizacion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrestacionUpdatableRelationshipsEquals(Prestacion expected, Prestacion actual) {
        assertThat(actual)
            .as("Verify Prestacion relationships")
            .satisfies(a -> assertThat(a.getNomenclador()).as("check nomenclador").isEqualTo(expected.getNomenclador()));
    }
}
