import { ColDef } from 'ag-grid-community';

import { agDateFilterParams, agDateOnlyFormatter, agDateValueGetter } from 'app/shared/ag-grid/ag-grid-utils';

/**
 * Genera la definición de columnas para la grilla AG Grid de Bioquimico
 */
export function getBioquimicoColumnDefs(actionsCellRenderer: any): ColDef[] {
  return [
    {
      field: 'id',
      headerName: 'Id',
      sortable: true,
      resizable: true,
      editable: true,
      width: 90,
      maxWidth: 110,
      pinned: 'left',
      filter: true,
    },
    {
      field: 'matricula',
      headerName: 'Matricula',
      sortable: true,
      resizable: true,
      editable: true,
      width: 120,
      filter: 'agNumberColumnFilter',
      cellDataType: 'number',
    },
    {
      field: 'cuit',
      headerName: 'Cuit',
      sortable: true,
      resizable: true,
      editable: true,
      flex: 1,
      minWidth: 150,
      filter: true,
    },
    {
      field: 'tipoIva',
      headerName: 'TipoIva',
      sortable: true,
      resizable: true,
      editable: true,
      flex: 1,
      minWidth: 150,
      filter: true,
    },
    {
      field: 'domicilioProfesional',
      headerName: 'DomicilioProfesional',
      sortable: true,
      resizable: true,
      editable: true,
      flex: 1,
      minWidth: 150,
      filter: true,
    },
    {
      field: 'estado',
      headerName: 'Estado',
      sortable: true,
      resizable: true,
      editable: true,
      flex: 1,
      minWidth: 150,
      filter: true,
    },
    {
      field: 'email',
      headerName: 'Email',
      sortable: true,
      resizable: true,
      editable: true,
      flex: 1,
      minWidth: 150,
      filter: true,
    },
    {
      field: 'fechaIngreso',
      headerName: 'FechaIngreso',
      sortable: true,
      resizable: true,
      editable: true,
      cellDataType: 'date',
      filter: 'agDateColumnFilter',
      filterParams: agDateFilterParams,
      valueGetter: agDateValueGetter('fechaIngreso'),
      valueFormatter: agDateOnlyFormatter,
      width: 140,
    },
    {
      field: 'telefono',
      headerName: 'Telefono',
      sortable: true,
      resizable: true,
      editable: true,
      flex: 1,
      minWidth: 150,
      filter: true,
    },
    {
      field: 'nombreEnDosep',
      headerName: 'NombreEnDosep',
      sortable: true,
      resizable: true,
      editable: true,
      flex: 1,
      minWidth: 150,
      filter: true,
    },
    {
      field: 'nroPrestadorOsde',
      headerName: 'NroPrestadorOsde',
      sortable: true,
      resizable: true,
      editable: true,
      width: 120,
      filter: 'agNumberColumnFilter',
      cellDataType: 'number',
    },
    {
      field: 'ingBrutos',
      headerName: 'IngBrutos',
      sortable: true,
      resizable: true,
      editable: true,
      flex: 1,
      minWidth: 150,
      filter: true,
    },
    {
      field: 'nroJubilacion',
      headerName: 'NroJubilacion',
      sortable: true,
      resizable: true,
      editable: true,
      flex: 1,
      minWidth: 150,
      filter: true,
    },
    {
      field: 'nroLaboratorio',
      headerName: 'NroLaboratorio',
      sortable: true,
      resizable: true,
      editable: true,
      flex: 1,
      minWidth: 150,
      filter: true,
    },
    {
      field: 'nombreCompleto',
      headerName: 'NombreCompleto',
      sortable: true,
      resizable: true,
      editable: true,
      flex: 1,
      minWidth: 150,
      filter: true,
    },
    {
      field: 'genero',
      headerName: 'Genero',
      sortable: true,
      resizable: true,
      editable: true,
      flex: 1,
      minWidth: 150,
      filter: true,
    },

    {
      // DEB user - user - user - login
      headerName: 'User',
      width: 150,
      sortable: true,
      filter: true,
      valueGetter: params => params.data?.user?.login,
      cellRenderer: (params: any) => {
        const item = params.data?.user;
        if (item) {
          return `<a href="/user/${item.id}/view">(${item.id}) ${item.login}</a>`;
        }
        return '';
      },
    },

    {
      headerName: 'Acciones',
      pinned: 'right',
      width: 130,
      sortable: false,
      filter: false,
      cellRenderer: actionsCellRenderer,
    },
  ];
}
